############## Make tests ###########################


all:
	make -C Zee
	make -C Zmumu
	make -C Wenu
	make -C Wmunu
	make -C Htautau
	make -C Ztautau
	make -C ttbar

clean:
	rm -f *~ */*~
	make -C Zee clean
	make -C Zmumu clean
	make -C Wenu clean
	make -C Wmunu clean
	make -C Htautau clean
	make -C Ztattau clean
	make -C ttbar clean

clobber:
	make -C Zee clobber
	make -C Zmumu clobber
	make -C Wenu clobber
	make -C Wmunu clobber
	make -C Htautau clobber
	make -C Ztautau clobber
	make -C ttbar clean
