EVENTS = 1000000

VIEWER=gv
COMPARE=../compare.sh

# Programs
PHOTOS_ONLY=../../photos_pythia_example.exe
PHOTOS_TAUOLA=../../photos_OFF_tauola.exe
# PHOTOS_TAUOLA=../../tauola_photos_pythia_example.exe

# Generation modes - PHOTOS_ONLY
DEFAULT_MODE =0 # ee@200GeV   (for Wenu, Wmunu, Zmumu)
TOP_MODE     =1 # ee@500GeV   (for ttbar)
PP_MODE      =2 # pp@1.4TeV   (for Zee)

# Generation modes - PHOTOS_TAUOLA
PIPI_MODE    =3 # ee@91.17GeV (for Ztautau) 
RHORHO_MODE  =4 # ee@500GeV   (for Htautau)
