EVENTS = 1000000

VIEWER=gv
COMPARE=../compare.sh

# Programs
PHOTOS_ONLY=../../photos_pythia_example.exe
PHOTOS_TAUOLA=../../tauola_photos_pythia_example.exe

# Generation modes - PHOTOS_ONLY
DEFAULT_MODE =0 # ee@200GeV   (for Wenu, Wmunu)
TOP_MODE     =1 # pp@1.4TeV   (for ttbar)
Z_EE_MODE    =2 # pp@1.4TeV   (for Zee)
Z_MU_MODE    =3 # ee@91.17GeV (for Zmumu)

# Generation modes - PHOTOS_TAUOLA
PIPI_MODE    =3 # ee@91.17GeV (for Ztautau)
RHORHO_MODE  =4 # ee@500GeV   (for Htautau)
