############## Make tests ###########################


all:
	make -C Zee
	make -C Zmumu
	make -C Wenu
	make -C Wnumu
	make -C Htautau


clean:
	rm -f *~
	make -C Zee clean
	make -C Zmumu clean
	make -C Wenu clean
	make -C Wnumu clean
	make -C Htautau clean

clobber: clean
	make -C Zee clobber
	make -C Zmumu clobber
	make -C Wenu clobber
	make -C Wnumu clobber
	make -C Htautau clobber
